"""
BCP47 to FLORES-200 map
"""
LANGUAGE_MAP = {
    'af': 'afr_Latn',  # Afrikaans
    'am': 'amh_Ethi',  # Amharic
    'ar': 'arb_Arab',  # Arabic
    'az': 'aze_Latn',  # Azerbaijani
    'be': 'bel_Cyrl',  # Belarusian
    'bg': 'bul_Cyrl',  # Bulgarian
    'bn': 'ben_Beng',  # Bengali
    'bs': 'bos_Latn',  # Bosnian
    'ca': 'cat_Latn',  # Catalan
    'cs': 'ces_Latn',  # Czech
    'cy': 'cym_Latn',  # Welsh
    'da': 'dan_Latn',  # Danish
    'de': 'deu_Latn',  # German
    'el': 'ell_Grek',  # Greek
    'en': 'eng_Latn',  # English
    'es': 'spa_Latn',  # Spanish
    'et': 'est_Latn',  # Estonian
    'eu': 'eus_Latn',  # Basque
    'fa': 'pes_Arab',  # Persian
    'fi': 'fin_Latn',  # Finnish
    'fr': 'fra_Latn',  # French
    'ga': 'gle_Latn',  # Irish
    'gl': 'glg_Latn',  # Galician
    'gu': 'guj_Gujr',  # Gujarati
    'he': 'heb_Hebr',  # Hebrew
    'hi': 'hin_Deva',  # Hindi
    'hr': 'hrv_Latn',  # Croatian
    'hu': 'hun_Latn',  # Hungarian
    'hy': 'hye_Armn',  # Armenian
    'id': 'ind_Latn',  # Indonesian
    'is': 'isl_Latn',  # Icelandic
    'it': 'ita_Latn',  # Italian
    'ja': 'jpn_Jpan',  # Japanese
    'jv': 'jav_Latn',  # Javanese
    'ka': 'kat_Geor',  # Georgian
    'kk': 'kaz_Cyrl',  # Kazakh
    'km': 'khm_Khmr',  # Khmer
    'kmr': 'kmr_Latn', # Kurmanji
    'kn': 'kan_Knda',  # Kannada
    'ko': 'kor_Hang',  # Korean
    'ky': 'kir_Cyrl',  # Kyrgyz
    'lo': 'lao_Laoo',  # Lao
    'lt': 'lit_Latn',  # Lithuanian
    'lv': 'lvs_Latn',  # Latvian
    'mk': 'mkd_Cyrl',  # Macedonian
    'ml': 'mal_Mlym',  # Malayalam
    'mn': 'mon_Cyrl',  # Mongolian
    'mr': 'mar_Deva',  # Marathi
    'ms': 'zsm_Latn',  # Malay
    'my': 'mya_Mymr',  # Burmese
    'ne': 'npi_Deva',  # Nepali
    'nl': 'nld_Latn',  # Dutch
    'no': 'nob_Latn',  # Norwegian
    'pa': 'pan_Guru',  # Punjabi
    'pl': 'pol_Latn',  # Polish
    'pt': 'por_Latn',  # Portuguese
    'ro': 'ron_Latn',  # Romanian
    'ru': 'rus_Cyrl',  # Russian
    'si': 'sin_Sinh',  # Sinhala
    'sk': 'slk_Latn',  # Slovak
    'sl': 'slv_Latn',  # Slovenian
    'sq': 'als_Latn',  # Albanian
    'sr': 'srp_Cyrl',  # Serbian
    'sv': 'swe_Latn',  # Swedish
    'sw': 'swh_Latn',  # Swahili
    'ta': 'tam_Taml',  # Tamil
    'te': 'tel_Telu',  # Telugu
    'th': 'tha_Thai',  # Thai
    'tr': 'tur_Latn',  # Turkish
    'uk': 'ukr_Cyrl',  # Ukrainian
    'ur': 'urd_Arab',  # Urdu
    'uz': 'uzn_Latn',  # Uzbek
    'vi': 'vie_Latn',  # Vietnamese
    'xh': 'xho_Latn',  # Xhosa
    'yi': 'ydd_Hebr',  # Yiddish
    'zh': 'zho_Hans',  # Chinese (Simplified)
    'zu': 'zul_Latn',  # Zulu
}
